swagger: "2.0"
info:
  description: "Progetto reti di calcolatori"
  version: "1.0.0"
  title: "Web-App"
host: "localhost:3000"
schemes:
- "http"
paths:
  /get/torneo:
    get:
      tags:
      - "Torneo"
      summary: "Crea torneo"
      description: ""
      consumes:
      - "string"
      produces:
      - "application/json"
      parameters:
        - in: query
          name: nome
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Torneo"
        "405":
          description: "Invalid input"
  /creatorneo:
    get:
      tags:
      - "Torneo"
      summary: "Get di un torneo in base al nome"
      description: ""
      consumes:
      - "string"
      produces:
      - "application/json"
      parameters:
      - name: nome
        in: query
        schema:
          type: "string"
        required: true
      - name: "date"
        in: query
        schema:
          type: "string"
        required: true
      responses:
        "201":
          description: "successful operation"
        "409":
          description: "Error"
  /delete/torneo:
    get:
      tags:
      - "Torneo"
      summary: "Elimina torneo"
      description: ""
      consumes:
      - "string"
      produces:
      - "application/json"
      parameters:
        - in: query
          name: nome
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "successful operation"
        "404":
          description: "Invalid input"
  /delete/user:
    get:
      tags:
      - "User"
      summary: "Elimina User"
      description: ""
      consumes:
      - "string"
      produces:
      - "application/json"
      parameters:
        - in: query
          name: nome
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "successful operation"
        "404":
          description: "Not found"
  /get/partite:
    get:
      tags:
      - "User"
      summary: "Get di una partita in base al nome"
      description: ""
      consumes:
      - "string"
      produces:
      - "application/json"
      parameters:
      - name: nome
        in: query
        schema:
          type: "string"
        required: true
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        "405":
          description: "Invalid input"
definitions:
  User:
    type: "object"
    properties:
      _id:
        type: "string"
      _rev:
        type: "string"
      game:
        type: "array"
        items:
          type: "object"
          properties:
            time_game:
              type: "integer"
            Partita:
              type: "string"
  Torneo:
    type: "object"
    properties:
      _id:
        type: "string"
      _rev:
        type: "string"
      nome:
        type: "string"
      date:
        type: "string"
    xml:
      name: "Torneo"
